/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TodoListImageWithRelations } from './todoListImageWithRelations';
import { TodoWithRelations } from './todoWithRelations';


/**
 * (Schema options: { includeRelations: true })
 */
export interface TodoListWithRelations { 
    id?: number;
    title: string;
    color?: string;
    todos?: Array<TodoWithRelations>;
    image?: TodoListImageWithRelations;
}

