/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TodoListWithRelations } from './todoListWithRelations';


/**
 * (Schema options: { includeRelations: true })
 */
export interface TodoWithRelations { 
    id?: number;
    title: string;
    desc?: string;
    isComplete?: boolean;
    todoListId?: number;
    todoList?: TodoListWithRelations;
}

