/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { InlineResponse200 } from '../model/inlineResponse200';
import { NewTodoInTodoList } from '../model/newTodoInTodoList';
import { Todo } from '../model/todo';
import { TodoPartial } from '../model/todoPartial';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class TodoListTodoControllerService {

    protected basePath = 'http://127.0.0.1:3000';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * @param id 
     * @param newTodoInTodoList 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public todoListTodoControllerCreate(id: number, newTodoInTodoList?: NewTodoInTodoList, observe?: 'body', reportProgress?: boolean): Observable<Todo>;
    public todoListTodoControllerCreate(id: number, newTodoInTodoList?: NewTodoInTodoList, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Todo>>;
    public todoListTodoControllerCreate(id: number, newTodoInTodoList?: NewTodoInTodoList, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Todo>>;
    public todoListTodoControllerCreate(id: number, newTodoInTodoList?: NewTodoInTodoList, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling todoListTodoControllerCreate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Todo>(`${this.configuration.basePath}/todo-lists/${encodeURIComponent(String(id))}/todos`,
            newTodoInTodoList,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param id 
     * @param where 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public todoListTodoControllerDelete(id: number, where?: { [key: string]: object; }, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse200>;
    public todoListTodoControllerDelete(id: number, where?: { [key: string]: object; }, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse200>>;
    public todoListTodoControllerDelete(id: number, where?: { [key: string]: object; }, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse200>>;
    public todoListTodoControllerDelete(id: number, where?: { [key: string]: object; }, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling todoListTodoControllerDelete.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (where !== undefined && where !== null) {
            queryParameters = queryParameters.set('where', <any>where);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<InlineResponse200>(`${this.configuration.basePath}/todo-lists/${encodeURIComponent(String(id))}/todos`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param id 
     * @param filter 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public todoListTodoControllerFind(id: number, filter?: { [key: string]: object; }, observe?: 'body', reportProgress?: boolean): Observable<Array<Todo>>;
    public todoListTodoControllerFind(id: number, filter?: { [key: string]: object; }, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Todo>>>;
    public todoListTodoControllerFind(id: number, filter?: { [key: string]: object; }, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Todo>>>;
    public todoListTodoControllerFind(id: number, filter?: { [key: string]: object; }, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling todoListTodoControllerFind.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('filter', <any>filter);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Array<Todo>>(`${this.configuration.basePath}/todo-lists/${encodeURIComponent(String(id))}/todos`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param id 
     * @param where 
     * @param todoPartial 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public todoListTodoControllerPatch(id: number, where?: { [key: string]: object; }, todoPartial?: TodoPartial, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse200>;
    public todoListTodoControllerPatch(id: number, where?: { [key: string]: object; }, todoPartial?: TodoPartial, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse200>>;
    public todoListTodoControllerPatch(id: number, where?: { [key: string]: object; }, todoPartial?: TodoPartial, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse200>>;
    public todoListTodoControllerPatch(id: number, where?: { [key: string]: object; }, todoPartial?: TodoPartial, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling todoListTodoControllerPatch.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (where !== undefined && where !== null) {
            queryParameters = queryParameters.set('where', <any>where);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch<InlineResponse200>(`${this.configuration.basePath}/todo-lists/${encodeURIComponent(String(id))}/todos`,
            todoPartial,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
